### ISSUE TITLE
Plugin preventing from mobs/animals to spawn

### ISSUE THREAD

**Issue by alondapro** [ShaneBeeStudios/HungerGames#2]
Hey, at the first time that I downloaded the plugin all worked fine.
But after a while, I don't know what is the exact reason animals and mobs stopped spawned.
Also I can't spawn them with an egg.

In my config --> settings I set the spawn-mobs to true but it also making the problem.
I tried to disable only this plugin and it actually worked, this means that plugin causing the problem.

My config file:

```yaml
# 
# Revamped by: ShaneBee
# 
# Issues: Please report issues on the BitBucket issue tracker @ https://bitbucket.org/ShaneBeeStudios/hungergames/issues?status=new&status=open
# Updates: Can be found on SpigotMC @ --- coming soon
# 
# More Info: See the wiki for more info on this config @ https://bitbucket.org/ShaneBeeStudios/HungerGames/wiki/Config.yml

settings:
  spawn-mobs: true
  spawn-mobs-interval: 35
  free-roam: 25
  bossbar-countdown: true
  trackingstick-uses: 5
  players-for-trackingstick: 10
  max-chestcontent: 9
  min-chestcontent: 1
  max-bonus-chestcontent: 5
  min-bonus-chestcontent: 1
  teleport-at-end: false
  teleport-at-end-time: 30
  max-team-size: 3
  globalexit: hgmap:546:151:1662:-0.59106445:-2.100482
reward:
  enabled: true
  cash: 200
  commands:
  - none
  messages:
  - none
random-chest:
  enabled: true
  interval: 90
  max-chestcontent: 9
rollback:
  allow-block-break: true
  blocks-per-second: 500
  protect-during-cooldown: true
  fix-leaves: true
  prevent-trampling: true
  editable-blocks:
  - ALL
world-border:
  enabled: true
  initiate-on-start: true
  countdown-start: 60
  countdown-end: 30
  final-border-size: 30
  center-on-first-spawn: true
spectate:
  enabled: true
  death-to-spectate: true
  hide-spectators: true
  fly: true
  chat: false
mcmmo:
  use-skills: false
  gain-experience: false
kits:
  Archer:
    permission: none
    helmet: LEATHER_HELMET color:red
    chestplate: LEATHER_CHESTPLATE color:red
    leggings: LEATHER_LEGGINGS color:red
    boots: LEATHER_BOOTS color:red
    items:
    - BOW name:&2לזמה_תשק
    - ARROW 64 name:&aלזמה_יצח
    - POTION potion:HEAL:60:0 2 name:&bהפרמ_יוקיש
  Knight:
    permission: none
    helmet: LEATHER_HELMET
    chestplate: LEATHER_CHESTPLATE color:green
    leggings: LEATHER_LEGGINGS color:green
    boots: LEATHER_BOOTS
    items:
    - STONE_SWORD 1 name:&7תיעוצקמ_ברח
    - BREAD 4 name:&6טושפ_םחל
    - SHIELD 1 name:&7יעוצקמ ןגמ
    - POTION potion:HEAL:60:0 2 name:&bהפרמ_יוקיש
  Turtle:
    permission: none
    helmet: TURTLE_HELMET name:&2בצ_לש_ןוירש
    items:
    - IRON_SWORD 1 name:&4לזרבמ_ברח
    - BREAD 4 name:&8עיבשמ_םחל
    - POTION potion:HEAL:60:0 2 name:&bהפרמ_יוקיש
  Ninja:
    permission: none
    helmet: LEATHER_HELMET color:black
    chestplate: LEATHER_CHESTPLATE color:black name:&7Ninja-Jacket lore:&6Ninja-Stealth-Suit:&4-------------
      enchant:fire_protection
    leggings: LEATHER_LEGGINGS color:black
    boots: LEATHER_BOOTS color:black enchant:feather_falling
    items:
    - POTION potion:HEAL:60:1 2 name:&bהפרמ_יוקיש_רפוס
    potion-effects:
    - SPEED:1:forever
  Miner:
    permission: none
    items:
    - STONE_PICKAXE 1 name:&4ןבאמ_שוכמ
    - LEGACY_RAW_BEEF 3 name:לשובמ_אל_רקב
  Survivor:
    permission: none
    helmet: LEATHER_HELMET color:black name:&3רועמ_הדסק
    items:
    - WOODEN_SWORD 1 name:&3ץעמ_ברח
    - LEGACY_RAW_CHICKEN 2 name:&3יח_ףוע
  Pyro:
    permission: none
    helmet: GOLDEN_HELMET color:yellow name:&7בהזמ_הדסק lore:&6!שאמ_ןיסח enchant:fire_protection
    chestplate: GOLDEN_CHESTPLATE color:yellow name:&7בהזמ_ןוירש lore:&6!שאמ_ןיסח
      enchant:fire_protection
    leggings: GOLDEN_LEGGINGS color:yellow name:&7בהזמ_תוניירושמ_םייסנכמ lore:&6!שאמ_ןיסח
      enchant:fire_protection
    boots: GOLDEN_BOOTS color:yellow name:&7בהזמ_תוניירושמ_םיילענ lore:&6!שאמ_ןיסח
      enchant:fire_protection
    items:
    - GOLDEN_SWORD 1 name:&7שאמ_ברח lore:&6!תפרוש enchant:fire_aspect
  stupidclass:
    permission: hg.vip
    items:
    - IRON_SWORD 1 enchant:sharpness:2 enchant:smite:2 name:&bOP_&6Sword?
    - BREAD 4
    - POTION potion:HEAL:60:2 2 name:&bהפרמ_יוקיש_רפוד_רפוס
    potion-effects:
    - FIRE_RESISTANCE:2:forever
```

Please check it out, thanks.
